import type { Metadata } from "next";
import { PageHeader } from "@/components/sections";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How InnoStarck collects, uses, and safeguards your personal information and IoT-generated data with engineering-grade security.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <section className="section">
      <div className="container legal">
        <PageHeader eyebrow="Legal" title="Privacy Policy" />
        <p className="legal__date">Effective Date: May 2, 2026</p>

        <h3>1. Introduction</h3>
        <p>
          At Inno Starck (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;), we prioritize your
          privacy and data security with the same engineering rigor we apply to our systems. This
          Privacy Policy details how we collect, use, and safeguard your personal information and
          IoT-generated data when you interact with our website and enterprise architectures.
        </p>

        <h3>2. Data Collection</h3>
        <p>We collect several types of data for various operational purposes:</p>
        <ul>
          <li>
            <strong>Provided Information:</strong> Contact details, names, and communication records
            when you request a partnership or technical support.
          </li>
          <li>
            <strong>Automated Telemetry:</strong> Log data, device information, and geographic
            location to ensure our web systems maintain high-concurrency performance and security.
          </li>
          <li>
            <strong>Hardware &amp; IoT Data:</strong> Data streams generated by integrated physical
            hardware managed by our systems, subject to specific client agreements.
          </li>
        </ul>

        <h3>3. Engineering-Grade Data Usage</h3>
        <p>
          We use your data strictly to operate, maintain, and optimize our digital infrastructures.
          We employ predictive modeling to identify bottlenecks and utilize AI-driven automation to
          enhance operational efficiency. Your data is never sold to third-party advertisers.
        </p>

        <h3>4. Security Protocols</h3>
        <p>
          We implement military and engineering-grade security measures. All communications and data
          storage mechanisms adhere to strict encryption protocols to prevent unauthorized access,
          alteration, or data destruction.
        </p>

        <h3>5. Contact Information</h3>
        <p>
          For questions regarding this policy or to exercise your data rights, contact our privacy
          compliance team at{" "}
          <a href="mailto:info@innostarck.com">info@innostarck.com</a>.
        </p>
      </div>
    </section>
  );
}
