export function PrivacyPolicy() {
    return (
        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
            <h1 className="text-4xl lg:text-5xl font-extrabold text-slate-900 mb-6">Privacy Policy</h1>
            <p className="text-slate-500 mb-10 border-b border-slate-200 pb-6">Effective Date: May 2, 2026</p>

            <div className="space-y-8 text-slate-700 leading-relaxed">
                <section>
                    <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Introduction</h2>
                    <p>At Inno Starck ("we," "our," or "us"), we prioritize your privacy and data security with the same engineering rigor we apply to our systems. This Privacy Policy details how we collect, use, and safeguard your personal information and IoT-generated data when you interact with our website and enterprise architectures.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Data Collection</h2>
                    <p className="mb-3">We collect several types of data for various operational purposes:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li><strong>Provided Information:</strong> Contact details, names, and communication records when you request a partnership or technical support.</li>
                        <li><strong>Automated Telemetry:</strong> Log data, device information, and geographic location to ensure our web systems maintain high-concurrency performance and security.</li>
                        <li><strong>Hardware & IoT Data:</strong> Data streams generated by integrated physical hardware managed by our systems, subject to specific client agreements.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-slate-900 mb-4">3. Engineering-Grade Data Usage</h2>
                    <p>We use your data strictly to operate, maintain, and optimize our digital infrastructures. We employ predictive modeling to identify bottlenecks and utilize AI-driven automation to enhance operational efficiency. Your data is never sold to third-party advertisers.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-slate-900 mb-4">4. Security Protocols</h2>
                    <p>We implement military and engineering-grade security measures. All communications and data storage mechanisms adhere to strict encryption protocols to prevent unauthorized access, alteration, or data destruction.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-slate-900 mb-4">5. Contact Information</h2>
                    <p>For questions regarding this policy or to exercise your data rights, contact our privacy compliance team at <a href="mailto:info@innostarck.com" className="text-blue-600 hover:underline">info@innostarck.com</a>.</p>
                </section>
            </div>
        </div>
    );
}

